apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gitea.fullname" . }}-ingress
  namespace: gitea-system
  labels:
    ingress.tmaxcloud.org/name: gitea
  annotations:
    cert-manager.io/cluster-issuer: tmaxcloud-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure

spec:
  ingressClassName: tmax-cloud
  {{- if .Values.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.hosts.subdomain }}.{{ .Values.ingress.hosts.domain }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.hosts.subdomain }}.{{ .Values.ingress.hosts.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "gitea.fullname" . }}-http
            port:
              number: 3000